# Generated by Django 4.0 on 2022-01-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=10, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
