# Generated by Django 4.0 on 2022-01-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0002_auto_20191219_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donorlist',
            name='token',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='allergies',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='any_diseases',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='bleeding_disorders',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='cardiac',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='hbsAg_hcv_hIV',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='last_donate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
