# Generated by Django 4.0 on 2022-01-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('dreg', '0003_donorlist_is_verified_donorlist_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeelist'),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
