# Generated by Django 4.0 on 2022-01-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0004_donorlist_staff_alter_donorlist_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorlist',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='donorlist',
            name='token',
        ),
    ]
